version: "3.3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  postgrest:
    image: postgrest/postgrest
    ports:
      - 3000:3000
    environment:
      PGRST_JWT_SECRET: ${POSTGREST_JWT_SECRET}
      PGRST_DB_URI: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/VegeStats_production
    depends_on:
      - postgres
  vegestats:
    build: .
    volumes:
      - .:/vegestats
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_PORT: 80
      RAILS_ENV: production
    ports:
      - "80:80"
    depends_on:
      - postgres