version: "3.3"

services:
  web:
    build: .
    container_name: web_container
    command: "bundle exec rails s -p $APP_PORT -b 0.0.0.0"
    ports:
      - "$APP_PORT:$APP_PORT"
    volumes:
      - ./:/vegestats