version: "3.3"

services:
  web:
    build: .
    container_name: web_container
    command: "bundle exec rails s -e development -p $APP_PORT -b 0.0.0.0"
    environment:
      POSTGREST_TOKEN: $POSTGREST_TOKEN
      POSTGREST_URL: $POSTGREST_URL
    ports:
      - "$APP_PORT:$APP_PORT"
    volumes:
      - ./:/vegestats