version: "3.3"

services:
  web:
    build: .
    container_name: web_container
    command: "bundle exec rails s -e development -p $APP_PORT -b 0.0.0.0"
    environment:
      POSTGREST_TOKEN: $POSTGREST_TOKEN
      POSTGREST_URL: $POSTGREST_URL
      APP_PORT: 80
    ports:
      - 80:80
    volumes:
      - ./:/vegestats
